export const SHOW_INSTRUCTIONS = "SHOW_INSTRUCTIONS";
export const SAVE_NAME = "SAVE_NAME";
export const SAVE_CLASS = "SAVE_CLASS";
export const CHANGE_LEVEL = "CHANGE_LEVEL";
export const SEND_MESSAGE = "SEND_MESSAGE";